apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: client
  template: 
    metadata:
      name: client-pods
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: imsuriyapi/todo-app:v4